[build]
  publish = "src"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[build]
  command = "npm install && npm run build"
  publish = "src"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# إعدادات خاصة بـ Node.js
[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--production=false"
